### PR TITLE
add PrivacyInfo.xcprivacy

### PR DESCRIPTION
**Pull request by tera-ny**
## ref links
https://github.com/cookpad/global-ios/issues/19954

## Why
以下の制限された機能にアクセスしている為
accessing the following restricted functions
- [contentModificationDateKey](https://developer.apple.com/documentation/foundation/urlresourcekey/1408803-contentmodificationdatekey)
  - [File timestamp APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278393) 
  - ユーティリティ関数内で使用している(0A2A.1 に該当していると思う)
     Used within a utility function (I believe it corresponds to 0A2A.1)
  - https://github.com/cookpad/ios-twitter-image-pipeline/blob/main/Sources/TwitterImagePipeline/TIPFileUtils.m
- mach_absolute_time
  -   [System boot time APIs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278394) は対応する理由が一つしかない(35F9.1)
       System boot time APIs have only one reason to support (35F9.1)

### CODE REVIEW

**Review by toya108 — APPROVED** [review]
Looks great!

**Review by toya108 — COMMENTED** [review]
It would be preferable to also update the ChangeLog.md.

https://github.com/cookpad/ios-twitter-image-pipeline/blob/main/CHANGELOG.md

**Comment by tera-ny** [comment]
added changelog 
https://github.com/cookpad/ios-twitter-image-pipeline/pull/3/commits/d20d6e8f9b20107a2128345c7cf89911380e87e5

**Comment by tera-ny** [comment]
@liamnichols 
Please review this PR for any problems 🙏 

If all is well, please merge and release as well. (I do not have the authority to proceed.)

**Review by liamnichols — COMMENTED** [review]
Thanks for this! Although do we need to take efforts for the .xcprivacy file to be included in Package.swift and the Podspec somehow? 

I'm not entirely sure how it all works, but I don't think adding the file alone is enough is it?

**Comment by tera-ny** [comment]
Added setting to bundle PrivacyInfo with package at https://github.com/cookpad/ios-twitter-image-pipeline/pull/3/commits/c2d3a55c87a58bb4abab73ff24edc03b06f31e7e 🙏

**Review by toya108 — COMMENTED** [review]
Looks good! 
But CI failed.
The code hasn't been changed, so it was probably an unstable test to begin with.
I wanted to rerun tests but I couldn't find rerun button.
It seems like I don't have the right to run Github Actions.

**Comment by liamnichols** [comment]
I restarted the test, and gave you correct access to the repo 🙇

**Comment by tera-ny** [comment]
After #5 is merged, I will incorporate the latest main in this PR to support CocoaPod as well. I will change the PR to draft status until the support is complete.

**Review by liamnichols — APPROVED** [review]
🚀

**Comment by tera-ny** [comment]
マージします！

**Pull request merged**
